added a placeholder texture, and moved us to a versioned folder layout
Para0234/SNS_AmbitionCosmic pull request #3
Opened 2024-12-11 23:48 UTC by xyzzy121

2024-12-12 02:15 UTC, Para0234 requested changes
Only issue is that we didn't think of the MayRequire="Ludeon.Rimworld.Biotech" to prevent the buildings from being accessible without the DLC.

2024-12-12 02:15 UTC, Para0234 commented on 1.5/Mods/Biotech/Defs/aotcGeneProcessors.xml
> +  <ThingDef ParentName="BuildingBase">
When creating something requiring a DLC, don't forget the tag "MayRequire="[Name of the mod]""

Here, I think the line should look like   <ThingDef ParentName="BuildingBase"  MayRequire="Ludeon.Rimworld.Biotech">

2024-12-12 02:15 UTC, Para0234 commented on 1.5/Mods/Biotech/Defs/aotcGeneProcessors.xml
> +  <ThingDef ParentName="BuildingBase">
Same as above, we don't want the building accessible without biotech enabled.

Here, I think the line should look like   <ThingDef ParentName="BuildingBase"  MayRequire="Ludeon.Rimworld.Biotech">

2024-12-12 02:40 UTC, Para0234 commented
The changes requested should be redundant with another change of the PR. I'll verify it as soon as I have the time to do so.

2024-12-12 20:32 UTC, xyzzy121 commented
alright, so they are implemented, (although using a placeholder texture.) the only thing left now is to balance them.

2024-12-16 23:00 UTC, Para0234 approved these changes

2024-12-21 02:11 UTC, merged